openapi: 3.2.0
info:
  title: Guardian Sysinfo API
  description: Guardian Authentication
  version: v1
servers:
- url: https://login.truste.com
  description: Generated server url
tags:
- name: Sysinfo
paths:
  /api/v1/sys_info:
    get:
      tags:
      - Sysinfo
      operationId: get_22
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SysInfo'
      security:
      - guardianAuth: []
      summary: Get 22
      x-summary-source: derived
components:
  schemas:
    SysInfo:
      properties:
        version:
          type: string
        buildTimestamp:
          type: integer
          format: int64
  securitySchemes:
    guardianAuth:
      type: oauth2
      scheme: bearer
      bearerFormat: JWT
      flows:
        implicit:
          authorizationUrl: https://login.truste.com/oauth/authorize
          tokenUrl: https://login.truste.com/oauth/token
          scopes:
            openid: OpenID
